[package]
name = "gravity"
version = "0.1.0"
authors = ["G. Endignoux <ggendx@gmail.com>"]
edition = "2021"

[features]
bigbench = []

[dependencies]
arrayref = "0.3.4"
byteorder = "1.1.0"
sha2 = "0.7.0"
hex = "0.3.1"
